### ISSUE TITLE
Problem with m3D_d_sLUT

### ISSUE THREAD

**Issue by dhthong92** [Forceflow/libmorton#18]
I attempt to encode the maximum bit of each coordinate, so x = y = z = 2^21 - 1, after that I run decode but I only get the right values of x and y, the value of z always wrong (I also tested with lower value like 2^20, 2^19). So I think maybe we have the problem with that function or did I use it with the wrong way? Anw, could you explain for me more about how decoding work? 

Another problem I want to ask is if I want to use morton code with 128 bits (so each x, y and z will have 42 bits), do I have to fixed anything? Because as you said before, your method is divide and conquer, so I think the number of bits is not a problem right?

Thanks for your help!

**Comment by Forceflow** [comment]
This is an edge case indeed. I'll test soon. 

Do you have the same problem when trying to use the decoding function with an _unshifted_ LUT table (m3D_d_LUT).

**Comment by dhthong92** [comment]
Sure that I used all unsigned integer value, I also used your code above to run but still not get a right value of z. Here is what I got: (2097151, 2097151, 898779)
Did I get a wrong version of this lib? I've just updated version by downloading master branch but still the same. Could you share your 2 files: morton3D.h and morton3D_LUTs.h for me to check it again?

**Comment by Forceflow** [comment]
I mask with NINE_BITS because my LUT table was made with that size in mind (3 bits from each coordinate). This is probably sub-optimal because I'm not memory-aligned this way, but it was the most straightforward thing to do at the time.

For 128 bits, I guess you could extend one of the existing methods, or split your coordinates in multiple parts manually and glue the pieces back together :) Try to rework one of the existing for-loop based methods, they are slower but easiest to grasp.
